language: c

before_install:
 - pushd magrathea/pbs_cache
 - make
 - sudo make install
 - popd

script:
 - autoreconf -ivf
 - CFLAGS="-std=gnu99 -pedantic -Wall -Wextra -D_POSIX_C_SOURCE=200112L -lrt" CXXFLAGS="-ansi -pedantic -Wall -Wextra -D_POSIX_C_SOURCE=200112L -lrt" ./configure --with-debug --with-rcp=scp --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-sendmail=/usr/sbin/sendmail --enable-syslog --enable-meta-fork
 - make

compiler: gcc
