#include <pbs_config.h>   /* the master config generated by configure */

#include <assert.h>
#include <ctype.h>
#include <memory.h>
#ifndef NDEBUG
#include <stdio.h>
#endif
#include <stdlib.h>
#include <string.h>
#include "pbs_ifl.h"
#include "list_link.h"
#include "attribute.h"
#include "pbs_error.h"

int to_size(char *, struct size_value *);

int decode_scratch(

  struct attribute *patr,  /* Modified on Return */
  char             *name,  /* attribute name */
  char             *rescn, /* I resource name - is used here */
  char             *val)   /* resource value */

{
	char *test = strdup(val);
	if (test == NULL)
		return PBSE_SYSTEM;

	char *delim1 = strchr(test,':');
	if (delim1 != NULL)
	{
		*delim1 = '\0';
		++delim1;
	}

	struct size_value size_value;
	if (to_size(test,&size_value) != 0)
		return PBSE_BADATVAL;

	if (delim1 == NULL)
		goto finished;

	char *delim2 = strchr(delim1,':');
	if (delim2 != NULL)
	{
		*delim2 = '\0';
		++delim2;
	}

	if ((strcmp(delim1,"local")  != 0) &&
		(strcmp(delim1,"shared") != 0) &&
	    (strcmp(delim1,"ssd")    != 0) &&
	    (strcmp(delim1,"first")  != 0))
		return PBSE_BADATVAL;

	if (delim2 == NULL)
		goto finished;

	if ((strcmp(delim2,"local")  != 0) &&
		(strcmp(delim2,"shared") != 0) &&
	    (strcmp(delim2,"ssd")    != 0) &&
	    (strcmp(delim2,"first")  != 0))
		return PBSE_BADATVAL;

finished:
	free(test);
	return decode_str(patr,name,rescn,val);
}
