#!/bin/bash

source $(dirname $0)/cluster_conf

# ensure cluster name param
if [ $# -ne 1 ]; then
	printf "No cluster name given\n\n"
	printf "Usage: $0 <cluster_name>\n\n"
	exit 1
fi

# Cache record

cache_record=`$list_cache $HOSTNAME cluster | $grep -w "$1"`

if [ "$cache_record" = "" ]; then
	printf "No record of cluster $1 in the cache\n"
	exit 1
fi

echo $cache_record | $awk '{printf "\nCluster records:\n  Cluster name:\t%s\n  Record ID:\t%s\n  Attributes:\t%s\n", $1, $2, $3}'

set_jobid $1

if [ "$jobid" = "" ]; then
        printf "Couldn't find JobID by qstat.\n"
        exit 1
fi

printf "  Job ID:\t$jobid\n"


printf "  Owner: \t"

echo $cache_record | $awk '{print $3}' | $sed 's/^.*owner=//' | $sed 's/[ \t;,].*$//'
vlan_id=`echo $cache_record | $awk '{print $3}' | $grep "vlan" | $sed 's/^.*vlan=//' | $sed 's/[ \t;,].*$//'`
if [ "$vlan_id" != "" ]; then
	printf "  VLAN: \t$vlan_id\n"

	sbftag=`$timeout 10 $sbf dumpstate | $grep -m 1 -A 10000 "vlan ID=\"$vlan_id\"" | $grep -m 1 -B 10000 "</vlan>" | $grep "<tag>" | $sed 's/<\/tag>//' | $sed 's/^.*>//'`
	printf "  sbfVLAN tag: \t$sbftag\n"

	sbfhosts=`$timeout 10 $sbf dumpstate | $grep -m 1 -A 10000 "vlan ID=\"$vlan_id\"" | $grep -m 1 -B 10000 "</vlan>" | $grep "<host>" | $sed 's/<\/host>//' | $sed 's/^.*>//' | $awk '{printf "%s ", $1}'`

	printf "  sbfVLAN host:\t$sbfhosts\n"


fi

# Machine list

printf "  Machines:\t"

$list_cache $HOSTNAME machine_cluster | $grep -E "$1\$" | $awk '{printf "%s ", $1}' 

shortid=`echo $jobid | awk -F . '{ print $1 }'`
$qstat -n $jobid | $grep $shortid | $awk '{printf "\n  Username:\t%s\n  Queue:\t%s\n  Elapsed:\t%s\n  State:\t%s\n  Time: \t%s\n", $2, $3, $9, $10, $11}'

printf "\n"


