#!/bin/bash

if [ ! -x /usr/sbin/magrathea-cmd ]; then
	exit 0;
fi

HOSTNAME=$(hostname -f);
STATUS=$(/usr/sbin/magrathea-cmd status | awk -F"[;-]" '{ print $1 }');
SOURCE=$(/usr/sbin/magrathea-cmd status | tr ';' '\n' | awk -F"[=]" '/lock=/ { print $2 }');

if [ "x$STATUS" == "xlocked" -a "x$SOURCE" == "x$HOSTNAME" ]; then
	/usr/sbin/magrathea-cmd unlock &>/dev/null
	exit $?
else
	logger -p daemon.warning -t magrathea_prologue "Magrathea race condition encountered (cannot unlock).";
	exit 255;
fi
