#!/bin/bash

user=$1
jobid=$2

if [ -f /var/spool/torque/aux/gpu-$jobid ]; then
	GPUS=`cat /var/spool/torque/aux/gpu-$jobid | sed 's/\/dev\/nvidia//g' | sort | tr '\n' ','`
	echo "CUDA_VISIBLE_DEVICES"
	echo "${GPUS%?}"
fi