#!/bin/bash

user=$1
jobid=$2

if [ -z "$user" ]; then exit 0; fi
if [ -z "$jobid" ]; then exit 0; fi

if [ -d /scratch.shared ]; then
	SCRATCH=/scratch.shared
elif [ -d /scratch ]; then
	SCRATCH=/scratch
else
	exit 0;
fi

if [ -d $SCRATCH/$user/job_$jobid ]; then
	echo "SCRATCH";
	echo "$SCRATCH/$user/job_$jobid";
	echo "SCRATCHDIR";
	echo "$SCRATCH/$user/job_$jobid";
fi
