#!/bin/bash

QNODES=
if [ -x /usr/bin/pbsnodes.bin ]; then
	QNODES=/usr/bin/pbsnodes.bin
elif [ -x /software/torque-2.4/bin/pbsnodes.bin ]; then
	QNODES=/software/torque-2.4/bin/pbsnodes.bin
fi

if [ "$QNODES" == "" ]; then
	echo "Couldn't find pbsnodes binary in /usr/bin/ or /software/torque-2.4/bin";
	exit 1;
fi

# MM 11/2006 Pokud chci vypsat vsechny uzly co jsou mimo PBS, ukaz i uzly
# v maintenace rezimu (pro PBS se tvari jako pouzitelne uzly)

if [ "$1" = "-l" ]
then
        $QNODES -a | awk\
        '\
                /^[a-z]/ {host=$1;c="";q="";} \
                /state =/ {state=$3;} \
                /comment =/ {$1="";$2="";c=$0; gsub("^  *", "", c); }\
                /queue =/ {q=$3;}\
                /^$/ {\
                        if (state!="free" && state!="job-busy" && \
                                        state!="job-exclusive" )\
                                print host"\t"state,c;\
                        else if (q!="") print host"\t"q;\
        }'
else
        $QNODES $@
fi

