#!/bin/bash

QNODES=
if [ -x /usr/bin/pbsnodes.bin ]; then
	QNODES=/usr/bin/pbsnodes.bin
elif [ -x /software/torque-2.4/bin/pbsnodes.bin ]; then
	QNODES=/software/torque-2.4/bin/pbsnodes.bin
fi

if [ "$QNODES" == "" ]; then
	echo "Couldn't find pbsnodes binary in /usr/bin/ or /software/torque-2.4/bin";
	exit 1;
fi

for arg in "$@"; do
	case "$arg" in
	-l)	$QNODES -a | awk '	/^[a-z]/ {host=$1;c="";q="";}
					/state =/ {state=$3;}
					/comment =/ {$1="";$2="";c=$0; gsub("^  *", "", c); }
					/queue =/ {q=$3;}
					/^$/ {
						if (state!="free" && state!="job-busy" && state!="job-exclusive" )
							print host"\t"state,c;
						else if (q!="") print host"\t"q;
						}'
		exit 0;;
	-*)	pargs="$pargs $arg";;
	*)	pargs="$pargs $(LC_ALL=C host -TtA $arg | awk '/has address/{ print $1 }')";;
	esac
done

$QNODES $pargs
