#! /bin/bash
# $Id: prologue.in,v 1.5 2007/12/10 23:17:01 xdenemar Exp $
#
# Started just before job execution by superior mom

JOBID="$1"
QSTAT=
if [ -x /usr/bin/qstat.bin ]; then
	QSTAT="/usr/bin/qstat.bin";
elif [ -x /software/torque-2.4/bin/qstat.bin ]; then
	QSTAT="/software/torque-2.4/bin/qstat.bin";
else
	exit 1;
fi

# Determine if this is a cluster job, if it is, don't do anything
if [ `$QSTAT -f $JOBID | grep "Resource_List.cluster" | wc -l` -ne 0 ]; then
	exit 0;
fi

if [ `$QSTAT -f $JOBID | sed -n 's/[ ]*resc_req_total.nodect[ ]*=[ ]*//p'` -gt 1 ]; then
	preempt=
else
	preempt='-preemptible'
fi

/usr/sbin/magrathea-cmd startjob$preempt "$JOBID" "1" &>/dev/null
if [$? -ne 0 ]; then
	exit 2;
fi

exit 0

