#! /bin/bash
# $Id: prologue.in,v 1.5 2007/12/10 23:17:01 xdenemar Exp $
#
# Started just before job execution by superior mom

JOBID="$1"
USER="$2"
GROUP="$3"

# GPU handling
source /var/spool/torque/mom_scripts/torque-sw-paths.sh

if [ "$PBS_UMASK" != "" ]; then
	umask $PBS_UMASK
else
	umask 077
fi


DIR="/scratch"
if [ "$TORQUE_RESC_SCRATCH_TYPE" = "local" ]; then
	if [ -d $DIR/$USER ]; then
		mkdir "$DIR/$USER/job_$JOBID" && chown "$USER" "$DIR/$USER/job_$JOBID" && chgrp "$GROUP" "$DIR/$USER/job_$JOBID" || exit 5;
	else
		exit 5;
	fi
fi

DIR="/scratch.shared"
if [ "$TORQUE_RESC_SCRATCH_TYPE" = "shared" ]; then
	if [ -d $DIR/$USER ]; then
		mkdir "$DIR/$USER/job_$JOBID" 2>/dev/null 1>&2;
		stat "$DIR/$USER/job_$JOBID" 2>/dev/null 1>&2 && chown "$USER" "$DIR/$USER/job_$JOBID" && chgrp "$GROUP" "$DIR/$USER/job_$JOBID" || exit 5;
	else
		exit 5;
	fi
fi

DIR="/scratch.ssd"
if [ "$TORQUE_RESC_SCRATCH_TYPE" = "ssd" ]; then
	if [ -d $DIR/$USER ]; then
		mkdir "$DIR/$USER/job_$JOBID" && chown "$USER" "$DIR/$USER/job_$JOBID" && chgrp "$GROUP" "$DIR/$USER/job_$JOBID" || exit 5;
	else
		exit 5;
	fi
fi

if [ "$TORQUE_RESC_GPU" != "" ]; then
	/var/spool/torque/mom_scripts/torque-gpu-mgr.sh $JOBID lock $TORQUE_RESC_GPU
	if [ $? -ne 0 ]; then
		exit 3;
	fi
fi

# custom prologue scripts
SCRIPTS_DIR='/var/spool/torque/mom_priv/prologue.d'
if [ -d "${SCRIPTS_DIR}" ]; then
	for F in "${SCRIPTS_DIR}"/*.sh; do
		if [ -x "${F}" ]; then
			source "${F}" || exit
		fi
	done
fi

# Cloud handling

if [ ! -x /usr/sbin/magrathea-cmd ]; then
	exit 0;
fi

# Determine if this is a cluster job, if it is, don't do anything
if [ "$TORQUE_RESC_TOTAL_CLUSTER" != "" ]; then
	/var/spool/torque/mom_scripts/magrathea_unlock
	#exit $?
	exit 0
fi

if [ $TORQUE_RESC_TOTAL_NODECT -gt 1 ]; then
	preempt=
else
	preempt='-preemptible'
fi

/usr/sbin/magrathea-cmd startjob$preempt "$JOBID" "$TORQUE_RESC_PROC" &>/dev/null
if [ $? -ne 0 ]; then
	exit 2;
fi

/var/spool/torque/mom_scripts/magrathea_unlock
#exit $?
exit 0

