#!/bin/bash

QSTAT=
QFREE=
if [ -x /usr/bin/qstat.bin ]; then
	QSTAT=/usr/bin/qstat.bin
elif [ -x /software/torque-2.4/bin/qstat.bin ]; then
	QSTAT=/software/torque-2.4/bin/qstat.bin
fi

if [ "$QSTAT" == "" ]; then
	echo "Could not find qstat binary in /usr/bin or /software/torque-2.4/bin";
	exit 1;
fi

$QSTAT $@
