#!/bin/bash

# Qsub wrapper for one step virtual cluster build/use

# Parse parameters that are either cluster=create only or cluster=use only

Wflag=
Wval=
Nflag=
Nval=
Iflag=
Gflag=
Gval=
while getopts W:N:IG:? name
do
	case $name in
        	W) Wflag=1
		   Wval="$OPTARG";;
		N) Nflag=1
		   Nval="$OPTARG";;
		I) Iflag=1;;
		G) Gflag=1
		   Gval="$OPTARG";;
		?) printf "Usage: %s: qsub params & args\n" $0
		   printf "Processed parameters: -I -W -G -N\n"
		   printf "Use -G group_name instead of -l group=group_name\n"
		   exit 2;;
	esac
done

shift $(($OPTIND - 1))

qsub_create_params="$*"
qsub_use_params="$*"

if [ ! -z "$Wflag" ]; then
	qsub_use_params="$qsub_use_params -W $Wval"
fi

if [ ! -z "$Iflag" ]; then
	qsub_use_params="$qsub_use_params -I"
fi

if [ -z "$Nflag" ]; then
	echo "Fatal error, no name specified."
	exit 1
else
	qsub_create_params="$qsub_create_params -l cluster=create -N $Nval"
	qsub_use_params="$qsub_use_params -l cluster=$Nval"
fi

printf "Building cluster with: \"qsub $qsub_create_params\"\n"

#qsub $qsub_create_params </dev/null

printf "Submiting into cluster with: \"qsub $qsub_use_params\"\n"

#qsub $qsub_use_params
