#!/bin/bash

source /var/spool/torque/mom_scripts/torque-scratch-mgr.sh

# LOCAL Scratches
SCRATCHES="/scratch /scratch.ssd"
for scr in $SCRATCHES; do

	if [ -d $scr ]; then
		find "$scr/" -maxdepth 2 -type f -name "*.size" | while read x; do

			if [ ! -d "$(dirname $x)/$(basename $x .size)" ]; then
				rm $x;
			fi

		done
	fi

	dead_quota_sum $scr >$scr/dead.size
done

CACHE_LIST=/software/pbs-7.0.0/cache/list_cache
CACHE_DELETE=/software/pbs-7.0.0/cache/delete_cache
SERVER=$(cat /var/spool/torque/server_name);

$CACHE_LIST $SERVER scratch_leftover | grep $(hostname) | grep -v scratch.shared | cut -f1 | while read x; do

	filename=$(echo $x | cut -d@ -f2 | cut -d: -f2);

	if [ ! -f $filename ]; then
		$CACHE_DELETE $SERVER $x scratch_leftover
	fi

done

