#!/bin/bash

source /var/spool/torque/mom_scripts/torque-sw-paths.sh
source /var/spool/torque/mom_scripts/torque-scratch-mgr.sh

# LOCAL Scratches
SCRATCHES="/scratch /scratch.ssd"
for scr in $SCRATCHES; do

	if [ -d $scr ]; then
		find "$scr/" -maxdepth 2 -type f -name "*.size" | while read x; do

			if [ ! -d "$(dirname $x)/$(basename $x .size)" ]; then
				rm $x;
			fi

		done

	dead_quota_sum $scr >$scr/.dead.size

	fi

done

$CACHE_LIST $SERVER scratch_leftover | grep $(hostname) | grep -v scratch.shared | cut -f1 | while read x; do

	filename=$(echo $x | cut -d@ -f2 | cut -d: -f2);

	if [ ! -f $filename ]; then
		$CACHE_DELETE $SERVER $x scratch_leftover
	fi

done

