#!/bin/bash

# hide all errors
exec >/dev/null 2>&1

# configuration
CACHE_UPDATE="/usr/local/sbin/update_cache"
PBS_SERVER=$(cat /var/spool/torque/server_name)
HOSTNAME=$(hostname -f)

########################
# REPORT LOCAL SCRATCH #
########################

if [ -d /scratch ]; then
	SCRATCHSIZE=$(df -Pk /scratch|grep -v Available|awk '{print $4;}')
else
	SCRATCHSIZE=0
fi

$CACHE_UPDATE $PBS_SERVER $HOSTNAME scratch_local $SCRATCHSIZE

######################
# REPORT SSD SCRATCH #
######################

if [ -d /ssd ]; then
	SCRATCHSIZE=$(df -Pk /ssd|grep -v Available|awk '{print $4;}')
else
	SCRATCHSIZE=0
fi

$CACHE_UPDATE $PBS_SERVER $HOSTNAME scratch_ssd $SCRATCHSIZE
