#!/bin/bash

# hide all errors
exec >/dev/null 2>&1

# configuration
if [ -x /usr/bin/update_cache ]; then
	CACHE_UPDATE="/usr/bin/update_cache"
elif [ -x /usr/sbin/update_cache ]; then
	CACHE_UPDATE="/usr/sbin/update_cache"
elif [ -x /usr/local/sbin/update_cache ]; then
	CACHE_UPDATE="/usr/local/sbin/update_cache"
fi

if [ "$CACHE_UPDATE" == "" ]; then
	exit 1
fi

PBS_SERVER=$(cat /var/spool/torque/server_name)
HOSTNAME=$(hostname -f)

########################
# REPORT LOCAL SCRATCH #
########################

if [ -d /scratch ]; then
	if [ "$(mount|cut -d\  -f3|grep /scratch|grep -v /scratch.)" !=  "" ]; then
		SCRATCHSIZE=$(df -Pk /scratch|grep -v Available|awk '{print $4;}')
		if [ -f /scratch/dead.size ]; then
			SCRATCHDEAD=$(cat /scratch/dead.size);
		else
			SCRATCHDEAD=0
		fi
	else
		SCRATCHSIZE=0
		SCRATCHDEAD=0
	fi
else
	SCRATCHSIZE=0
	SCRATCHDEAD=0
fi

$CACHE_UPDATE $PBS_SERVER $HOSTNAME scratch_local $SCRATCHSIZE\;$SCRATCHDEAD

######################
# REPORT SSD SCRATCH #
######################

if [ -d /scratch.ssd ]; then
	if [ "$(mount|cut -d\  -f3|grep /scratch.ssd)" != "" ]; then
		SCRATCHSIZE=$(df -Pk /scratch.ssd|grep -v Available|awk '{print $4;}')
		if [ -f /scratch.ssd/dead.size ]; then
			SCRATCHDEAD=$(cat /scratch.ssd/dead.size);
		else
			SCRATCHDEAD=0
		fi
	else
		SCRATCHSIZE=0
		SCRATCHDEAD=0
	fi
else
	SCRATCHSIZE=0
	SCRATCHDEAD=0
fi

$CACHE_UPDATE $PBS_SERVER $HOSTNAME scratch_ssd $SCRATCHSIZE\;$SCRATCHDEAD
