#!/bin/sh
#
# sbf_stop
#
RAW_PARAMS="$*"

ex=0

SBF_BIN=/software/magrathea/bin/sbf
NEW_VLAN=1

if [ $1 == "-k" ]; then
	NEW_VLAN=0;
	shift;
fi

my_vlan=$1
shift

# slartibartfast_client removehosts MojeVLAN host_1 host_2 host_3
# slartibartfast_client releasevlan MojeVLAN

if [ -x $SBF_BIN ]; then
        $SBF_BIN -q removehosts $my_vlan $* 
        if [ $? != 0 ]; then ex=1;fi
        #$SBF_BIN -q releasevlan $my_vlan
        #if [ $? != 0 ]; then ex=2;fi
	if [ $NEW_VLAN -eq 1 ]; then
	        $SBF_BIN -q forcereleasevlan $my_vlan
        	if [ $? != 0 ]; then ex=2;fi
	fi
fi      

if [ $ex = 0 ]; then
  echo "ok"
else 
  echo "fail"
fi
exit $ex
