#!/bin/bash
# Chmatak Ivan (c) 2014
# - regularly touch SCRATCHDIR of running jobs

# determinine running jobs from momctl
JOBS=`/usr/sbin/momctl -q jobs 2>/dev/null`
if [ $? -ne 0 ]
then
	sleep 10
	JOBS=`/usr/sbin/momctl -q jobs 2>/dev/null`
	if [ $? -ne 0 ]
	then
		logger -p daemon.err -t scratch_cleanup "Could not get list of running jobs from momctl."
		exit 0
	fi
fi

for i in `echo "$JOBS" |sed "s/.* 'jobs=//"| sed "s/'//"`
do
	# determine scratch directory
        user=`/usr/bin/printjob /var/spool/torque/mom_priv/jobs/$i.JB 2>/dev/null| grep "^euser"| sed 's/euser = //'`;
	host=`hostname`
        type=`/usr/bin/printjob /var/spool/torque/mom_priv/jobs/$i.JB 2>/dev/null| grep "^sched_nodespec"| sed 's/+/\n/'| grep "$host"| grep scratch_type| sed 's/.*scratch_type=//'|sed 's/:.*//'`;

	if [ -z "$type" ]; then exit 0; fi # nektere chyby jsou normalni (type neni nastaven u jobu, ktere stavi virtualni clustery)
	if [ -z "$user" -o -z "$host" ]; then echo "Pro $i je type/user/host prazdny, koncim"; exit 1; fi # jine vazne

	# touch the directory
        if [ $type = local ]; then type=''; else type='.'$type; fi;
        touch -c /scratch${type}/${user}/job_$i 2>/dev/null;
done
