/*
 * decode_DIS_SchedLock() - decode a Scheduler lock batch request
 *
 * The batch_request structure must already exist (be allocated by the
 * caller.   It is assumed that the header fields (protocol type,
 * protocol version, request type, and user name) have already be decoded.
 *
 * Data items are: u int  manner
 */

#include <pbs_config.h>   /* the master config generated by configure */

#include <sys/types.h>
#include "libpbs.h"
#include "list_link.h"
#include "server_limits.h"
#include "attribute.h"
#include "credential.h"
#include "batch_request.h"
#include "dis.h"

int decode_DIS_SchedLock(int sock, struct batch_request *preq)
  {
  int rc;

  preq->rq_ind.rq_lock = disrui(sock, &rc);

  return rc;
  }
