/*
 * encode_DIS_SchedLock() - encode a Scheduler lock batch requests
 *
 * Data items are: unsigned int manner
 */

#include <pbs_config.h>   /* the master config generated by configure */

#include "libpbs.h"
#include "pbs_error.h"
#include "dis.h"

int encode_DIS_SchedLock(int sock, int action)
  {
  return (diswui(sock, action));
  }
