/* pbs_lock

*/

#include <pbs_config.h>   /* the master config generated by configure */

#include <string.h>
#include <stdio.h>
#include "libpbs.h"
#include "dis.h"

int pbs_lock(

  int   c,      /* I */
  int   action, /* I */
  char *extend) /* I */

  {

  struct batch_reply *reply;

  int rc = 0;
  int sock;

  /* send request */

  sock = connection[c].ch_socket;

  /* setup DIS support routines for following DIS calls */

  DIS_tcp_setup(sock);

  if ((rc = encode_DIS_ReqHdr(sock, PBS_BATCH_SchedulerLock, pbs_current_user)) ||
      (rc = encode_DIS_SchedLock(sock, action)) ||
      (rc = encode_DIS_ReqExtend(sock, extend)))
    {
    connection[c].ch_errtxt = strdup(dis_emsg[rc]);

    pbs_errno = PBSE_PROTOCOL;

    return(pbs_errno);
    }

  if (DIS_tcp_wflush(sock))
    {
    pbs_errno = PBSE_PROTOCOL;

    return(pbs_errno);
    }

  /* read in reply */

  reply = PBSD_rdrpy(c);
  rc = connection[c].ch_errno;

  PBSD_FreeReply(reply);

  return(rc);
  }  /* END pbs_terminate() */
